const NON_ARAB_COUNTRIES = [
  { value: "Afghanistan", labelAr: "أفغانستان", label: "Afghanistan" },
  { value: "Aland Islands", labelAr: "جزر أولاند", label: "Aland Islands" },
  { value: "Albania", labelAr: "ألبانيا", label: "Albania" },
  {
    value: "American Samoa",
    labelAr: "ساموا الأمريكية",
    label: "American Samoa",
  },
  { value: "Andorra", labelAr: "أندورا", label: "Andorra" },
  { value: "Angola", labelAr: "أنغولا", label: "Angola" },
  { value: "Anguilla", labelAr: "أنغويلا", label: "Anguilla" },
  { value: "Antarctica", labelAr: "أنتاركتيكا", label: "Antarctica" },
  {
    value: "Antigua and Barbuda",
    labelAr: "أنتيغوا وباربودا",
    label: "Antigua and Barbuda",
  },
  { value: "Argentina", labelAr: "الأرجنتين", label: "Argentina" },
  { value: "Armenia", labelAr: "أرمينيا", label: "Armenia" },
  { value: "Aruba", labelAr: "أروبا", label: "Aruba" },
  { value: "Australia", labelAr: "أستراليا", label: "Australia" },
  { value: "Austria", labelAr: "النمسا", label: "Austria" },
  { value: "Azerbaijan", labelAr: "أذربيجان", label: "Azerbaijan" },
  { value: "Bahamas", labelAr: "الباهاما", label: "Bahamas" },
  { value: "Bangladesh", labelAr: "بنغلاديش", label: "Bangladesh" },
  { value: "Barbados", labelAr: "باربادوس", label: "Barbados" },
  { value: "Belarus", labelAr: "بيلاروسيا", label: "Belarus" },
  { value: "Belgium", labelAr: "بلجيكا", label: "Belgium" },
  { value: "Belize", labelAr: "بليز", label: "Belize" },
  { value: "Benin", labelAr: "بنين", label: "Benin" },
  { value: "Bermuda", labelAr: "برمودا", label: "Bermuda" },
  { value: "Bhutan", labelAr: "بوتان", label: "Bhutan" },
  {
    value: "Bolivia (Plurinational State of)",
    labelAr: "بوليفيا",
    label: "Bolivia",
  },
  {
    value: "Bonaire, Sint Eustatius and Saba",
    labelAr: "بونير، سينت أوستاتيوس وسابا",
    label: "Bonaire, Sint Eustatius and Saba",
  },
  {
    value: "Bosnia and Herzegovina",
    labelAr: "البوسنة والهرسك",
    label: "Bosnia and Herzegovina",
  },
  { value: "Botswana", labelAr: "بوتسوانا", label: "Botswana" },
  { value: "Bouvet Island", labelAr: "جزيرة بوفيت", label: "Bouvet Island" },
  { value: "Brazil", labelAr: "البرازيل", label: "Brazil" },
  {
    value: "British Indian Ocean Territory",
    labelAr: "إقليم المحيط الهندي البريطاني",
    label: "British Indian Ocean Territory",
  },
  {
    value: "Brunei Darussalam",
    labelAr: "بروناي دار السلام",
    label: "Brunei Darussalam",
  },
  { value: "Bulgaria", labelAr: "بلغاريا", label: "Bulgaria" },
  { value: "Burkina Faso", labelAr: "بوركينا فاسو", label: "Burkina Faso" },
  { value: "Burundi", labelAr: "بوروندي", label: "Burundi" },
  { value: "Cabo Verde", labelAr: "الرأس الأخضر", label: "Cabo Verde" },
  { value: "Cambodia", labelAr: "كمبوديا", label: "Cambodia" },
  { value: "Cameroon", labelAr: "الكاميرون", label: "Cameroon" },
  { value: "Canada", labelAr: "كندا", label: "Canada" },
  { value: "Cayman Islands", labelAr: "جزر كايمان", label: "Cayman Islands" },
  {
    value: "Central African Republic",
    labelAr: "جمهورية أفريقيا الوسطى",
    label: "Central African Republic",
  },
  { value: "Chad", labelAr: "تشاد", label: "Chad" },
  { value: "Chile", labelAr: "تشيلي", label: "Chile" },
  { value: "China", labelAr: "الصين", label: "China" },
  {
    value: "Christmas Island",
    labelAr: "جزيرة الكريسماس",
    label: "Christmas Island",
  },
  {
    value: "Cocos (Keeling) Islands",
    labelAr: "جزر كوكوس",
    label: "Cocos (Keeling) Islands",
  },
  { value: "Colombia", labelAr: "كولومبيا", label: "Colombia" },
  { value: "Comoros", labelAr: "جزر القمر", label: "Comoros" },
  { value: "Congo", labelAr: "الكونغو", label: "Congo" },
  {
    value: "Congo (the Democratic Republic of Congo)",
    labelAr: "جمهورية الكونغو الديمقراطية",
    label: "Congo (the Democratic Republic of Congo)",
  },
  { value: "Cook Islands", labelAr: "جزر كوك", label: "Cook Islands" },
  { value: "Costa Rica", labelAr: "كوستاريكا", label: "Costa Rica" },
  { value: "Côte d'Ivoire", labelAr: "ساحل العاج", label: "Côte d'Ivoire" },
  { value: "Croatia", labelAr: "كرواتيا", label: "Croatia" },
  { value: "Cuba", labelAr: "كوبا", label: "Cuba" },
  { value: "Curaçao", labelAr: "كوراساو", label: "Curaçao" },
  { value: "Cyprus", labelAr: "قبرص", label: "Cyprus" },
  { value: "Czechia", labelAr: "التشيك", label: "Czechia" },
  { value: "Denmark", labelAr: "الدنمارك", label: "Denmark" },
  { value: "Dominica", labelAr: "دومينيكا", label: "Dominica" },
  {
    value: "Dominican Republic",
    labelAr: "جمهورية الدومينيكان",
    label: "Dominican Republic",
  },
  { value: "Ecuador", labelAr: "الإكوادور", label: "Ecuador" },
  { value: "El Salvador", labelAr: "السلفادور", label: "El Salvador" },
  {
    value: "Equatorial Guinea",
    labelAr: "غينيا الاستوائية",
    label: "Equatorial Guinea",
  },
  { value: "Eritrea", labelAr: "إريتريا", label: "Eritrea" },
  { value: "Estonia", labelAr: "إستونيا", label: "Estonia" },
  { value: "Ethiopia", labelAr: "إثيوبيا", label: "Ethiopia" },
  {
    value: "Falkland Islands (Malvinas)",
    labelAr: "جزر فوكلاند",
    label: "Falkland Islands (Malvinas)",
  },
  {
    value: "Faroe Islands (the)",
    labelAr: "جزر فارو",
    label: "Faroe Islands (the)",
  },
  { value: "Fiji", labelAr: "فيجي", label: "Fiji" },
  { value: "Finland", labelAr: "فنلندا", label: "Finland" },
  { value: "France", labelAr: "فرنسا", label: "France" },
  { value: "French Guiana", labelAr: "غيانا الفرنسية", label: "French Guiana" },
  {
    value: "French Polynesia",
    labelAr: "بولينيزيا الفرنسية",
    label: "French Polynesia",
  },
  {
    value: "French Southern Territories",
    labelAr: "المقاطعات الجنوبية الفرنسية",
    label: "French Southern Territories",
  },
  { value: "Gabon", labelAr: "الغابون", label: "Gabon" },
  { value: "Gambia", labelAr: "غامبيا", label: "Gambia" },
  { value: "Georgia", labelAr: "جورجيا", label: "Georgia" },
  { value: "Germany", labelAr: "ألمانيا", label: "Germany" },
  { value: "Ghana", labelAr: "غانا", label: "Ghana" },
  { value: "Gibraltar", labelAr: "جبل طارق", label: "Gibraltar" },
  { value: "Greece", labelAr: "اليونان", label: "Greece" },
  { value: "Greenland", labelAr: "جرينلاند", label: "Greenland" },
  { value: "Grenada", labelAr: "غرينادا", label: "Grenada" },
  { value: "Guadeloupe", labelAr: "جزر جوادلوب", label: "Guadeloupe" },
  { value: "Guam", labelAr: "غوام", label: "Guam" },
  { value: "Guatemala", labelAr: "غواتيمالا", label: "Guatemala" },
  { value: "Guernsey", labelAr: "غيرنسي", label: "Guernsey" },
  { value: "Guinea", labelAr: "غينيا", label: "Guinea" },
  { value: "Guinea-Bissau", labelAr: "غينيا بيساو", label: "Guinea-Bissau" },
  { value: "Guyana", labelAr: "غيانا", label: "Guyana" },
  { value: "Haiti", labelAr: "هايتي", label: "Haiti" },
  {
    value: "Heard Island and McDonald Islands",
    labelAr: "جزيرة هيرد وجزر ماكدونالد",
    label: "Heard Island and McDonald Islands",
  },
  { value: "Holy See", labelAr: "الكرسي الرسولي", label: "Holy See" },
  { value: "Honduras", labelAr: "هندوراس", label: "Honduras" },
  { value: "Hong Kong", labelAr: "هونغ كونغ", label: "Hong Kong" },
  { value: "Hungary", labelAr: "هنغاريا", label: "Hungary" },
  { value: "Iceland", labelAr: "آيسلندا", label: "Iceland" },
  { value: "India", labelAr: "الهند", label: "India" },
  { value: "Indonesia", labelAr: "إندونيسيا", label: "Indonesia" },
  { value: "Iran", labelAr: "إيران", label: "Iran" },
  { value: "Ireland", labelAr: "أيرلندا", label: "Ireland" },
  { value: "Italy", labelAr: "إيطاليا", label: "Italy" },
  { value: "Jamaica", labelAr: "جامايكا", label: "Jamaica" },
  { value: "Japan", labelAr: "اليابان", label: "Japan" },
  { value: "Jersey", labelAr: "جيرسي", label: "Jersey" },
  { value: "Kazakhstan", labelAr: "كازاخستان", label: "Kazakhstan" },
  { value: "Kenya", labelAr: "كينيا", label: "Kenya" },
  { value: "Kiribati", labelAr: "كيريباس", label: "Kiribati" },
  {
    value: "Korea (Democratic Republic of Korea)",
    labelAr: "كوريا الشمالية",
    label: "Korea (Democratic Republic of Korea)",
  },
  {
    value: "Korea (Republic of Korea)",
    labelAr: "كوريا الجنوبية",
    label: "Korea (Republic of Korea)",
  },
  { value: "Kyrgyzstan", labelAr: "قيرغيزستان", label: "Kyrgyzstan" },
  {
    value: "Lao People's Democratic Republic",
    labelAr: "جمهورية لاو الديمقراطية الشعبية",
    label: "Lao People's Democratic Republic",
  },
  { value: "Latvia", labelAr: "لاتفيا", label: "Latvia" },
  { value: "Lesotho", labelAr: "ليسوتو", label: "Lesotho" },
  { value: "Liberia", labelAr: "ليبيريا", label: "Liberia" },
  { value: "Liechtenstein", labelAr: "ليختنشتاين", label: "Liechtenstein" },
  { value: "Lithuania", labelAr: "ليتوانيا", label: "Lithuania" },
  { value: "Luxembourg", labelAr: "لوكسمبورغ", label: "Luxembourg" },
  { value: "Macao", labelAr: "ماكاو", label: "Macao" },
  {
    value: "Macedonia (former Yugoslavia)",
    labelAr: "مقدونيا",
    label: "Macedonia",
  },
  { value: "Madagascar", labelAr: "مدغشقر", label: "Madagascar" },
  { value: "Malawi", labelAr: "مالاوي", label: "Malawi" },
  { value: "Malaysia", labelAr: "ماليزيا", label: "Malaysia" },
  { value: "Maldives", labelAr: "المالديف", label: "Maldives" },
  { value: "Mali", labelAr: "مالي", label: "Mali" },
  { value: "Malta", labelAr: "مالطا", label: "Malta" },
  {
    value: "Marshall Islands",
    labelAr: "جزر مارشال",
    label: "Marshall Islands",
  },
  { value: "Martinique", labelAr: "مارتينيك", label: "Martinique" },
  { value: "Mauritius", labelAr: "موريشيوس", label: "Mauritius" },
  { value: "Mayotte", labelAr: "مايوت", label: "Mayotte" },
  { value: "Mexico", labelAr: "المكسيك", label: "Mexico" },
  {
    value: "Micronesia (Federated States of)",
    labelAr: "ولايات ميكرونيزيا المتحدة",
    label: "Micronesia (Federated States of)",
  },
  {
    value: "Moldova (Republic of Moldova)",
    labelAr: "مولدوفا",
    label: "Moldova (Republic of Moldova)",
  },
  { value: "Monaco", labelAr: "موناكو", label: "Monaco" },
  { value: "Mongolia", labelAr: "منغوليا", label: "Mongolia" },
  { value: "Montenegro", labelAr: "الجبل الأسود", label: "Montenegro" },
  { value: "Montserrat", labelAr: "مونتسرات", label: "Montserrat" },
  { value: "Mozambique", labelAr: "موزمبيق", label: "Mozambique" },
  { value: "Myanmar", labelAr: "ميانمار", label: "Myanmar" },
  { value: "Namibia", labelAr: "ناميبيا", label: "Namibia" },
  { value: "Nauru", labelAr: "ناورو", label: "Nauru" },
  { value: "Nepal", labelAr: "نيبال", label: "Nepal" },
  { value: "Netherlands", labelAr: "هولندا", label: "Netherlands" },
  {
    value: "New Caledonia",
    labelAr: "كاليدونيا الجديدة",
    label: "New Caledonia",
  },
  { value: "New Zealand", labelAr: "نيوزيلندا", label: "New Zealand" },
  { value: "Nicaragua", labelAr: "نيكاراغوا", label: "Nicaragua" },
  { value: "Niger", labelAr: "النيجر", label: "Niger" },
  { value: "Nigeria", labelAr: "نيجيريا", label: "Nigeria" },
  { value: "Niue", labelAr: "نيوي", label: "Niue" },
  {
    value: "Norfolk Island",
    labelAr: "جزيرة نورفولك",
    label: "Norfolk Island",
  },
  {
    value: "Northern Mariana Islands",
    labelAr: "جزر ماريانا الشمالية",
    label: "Northern Mariana Islands",
  },
  { value: "Norway", labelAr: "النرويج", label: "Norway" },
  { value: "Not defined", labelAr: "غير معرف", label: "Not defined" },
  {
    value: "Other nationalities (explain)",
    labelAr: "جنسيات أخرى",
    label: "Other nationalities (explain)",
  },
  { value: "Pakistan", labelAr: "باكستان", label: "Pakistan" },
  { value: "Palau", labelAr: "بالاو", label: "Palau" },
  { value: "Panama", labelAr: "بنما", label: "Panama" },
  {
    value: "Papua New Guinea",
    labelAr: "بابوا غينيا الجديدة",
    label: "Papua New Guinea",
  },
  { value: "Paraguay", labelAr: "باراغواي", label: "Paraguay" },
  { value: "Peru", labelAr: "بيرو", label: "Peru" },
  { value: "Philippines", labelAr: "الفلبين", label: "Philippines" },
  { value: "Pitcairn", labelAr: "جزر بيتكيرن", label: "Pitcairn" },
  { value: "Poland", labelAr: "بولندا", label: "Poland" },
  { value: "Portugal", labelAr: "البرتغال", label: "Portugal" },
  { value: "Puerto Rico", labelAr: "بورتوريكو", label: "Puerto Rico" },
  { value: "Réunion", labelAr: "ريونيون", label: "Réunion" },
  { value: "Romania", labelAr: "رومانيا", label: "Romania" },
  {
    value: "Russian Federation",
    labelAr: "روسيا",
    label: "Russian Federation",
  },
  { value: "Rwanda", labelAr: "رواندا", label: "Rwanda" },
  {
    value: "Saint Barthélemy",
    labelAr: "سانت بارتيليمي",
    label: "Saint Barthélemy",
  },
  {
    value: "Saint Helena, Ascension and Tristan da Cunha",
    labelAr: "سانت هيلينا، أسينسيون وتريستان دا كونها",
    label: "Saint Helena, Ascension and Tristan da Cunha",
  },
  {
    value: "Saint Kitts and Nevis",
    labelAr: "سانت كيتس ونيفيس",
    label: "Saint Kitts and Nevis",
  },
  { value: "Saint Lucia", labelAr: "سانت لوسيا", label: "Saint Lucia" },
  {
    value: "Saint Martin French part",
    labelAr: "سانت مارتن الجزء الفرنسي",
    label: "Saint Martin French part",
  },
  {
    value: "Saint Pierre and Miquelon",
    labelAr: "سان بيير وميكلون",
    label: "Saint Pierre and Miquelon",
  },
  {
    value: "Saint Vincent and the Grenadines",
    labelAr: "سانت فنسنت والغرينادين",
    label: "Saint Vincent and the Grenadines",
  },
  { value: "Samoa", labelAr: "ساموا", label: "Samoa" },
  { value: "San Marino", labelAr: "سان مارينو", label: "San Marino" },
  {
    value: "Sao Tome and Principe",
    labelAr: "ساو تومي وبرينسيبي",
    label: "Sao Tome and Principe",
  },
  { value: "Senegal", labelAr: "السنغال", label: "Senegal" },
  { value: "Serbia", labelAr: "صربيا", label: "Serbia" },
  { value: "Seychelles", labelAr: "سيشيل", label: "Seychelles" },
  { value: "Sierra Leone", labelAr: "سيراليون", label: "Sierra Leone" },
  { value: "Singapore", labelAr: "سنغافورة", label: "Singapore" },
  {
    value: "Sint Maarten Dutch part",
    labelAr: "سينت مارتن الجزء الهولندي",
    label: "Sint Maarten Dutch part",
  },
  { value: "Slovakia", labelAr: "سلوفاكيا", label: "Slovakia" },
  { value: "Slovenia", labelAr: "سلوفينيا", label: "Slovenia" },
  { value: "Solomon Islands", labelAr: "جزر سليمان", label: "Solomon Islands" },
  { value: "South Africa", labelAr: "جنوب أفريقيا", label: "South Africa" },
  {
    value: "South Georgia and the South Sandwich Islands",
    labelAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    label: "South Georgia and the South Sandwich Islands",
  },
  { value: "South Sudan", labelAr: "جنوب السودان", label: "South Sudan" },
  { value: "Spain", labelAr: "إسبانيا", label: "Spain" },
  { value: "Sri Lanka", labelAr: "سريلانكا", label: "Sri Lanka" },
  { value: "Suriname", labelAr: "سورينام", label: "Suriname" },
  {
    value: "Svalbard and Jan Mayen",
    labelAr: "سفالبارد ويان ماين",
    label: "Svalbard and Jan Mayen",
  },
  { value: "Swaziland", labelAr: "سوازيلاند", label: "Swaziland" },
  { value: "Sweden", labelAr: "السويد", label: "Sweden" },
  { value: "Switzerland", labelAr: "سويسرا", label: "Switzerland" },
  {
    value: "Taiwan (Province of China)",
    labelAr: "تايوان",
    label: "Taiwan (Province of China)",
  },
  { value: "Tajikistan", labelAr: "طاجيكستان", label: "Tajikistan" },
  {
    value: "Tanzania, United Republic of Tanzania",
    labelAr: "تنزانيا",
    label: "Tanzania, United Republic of Tanzania",
  },
  { value: "Thailand", labelAr: "تايلاند", label: "Thailand" },
  { value: "Timor-Leste", labelAr: "تيمور الشرقية", label: "Timor-Leste" },
  { value: "Togo", labelAr: "توغو", label: "Togo" },
  { value: "Tokelau", labelAr: "توكيلاو", label: "Tokelau" },
  { value: "Tonga", labelAr: "تونغا", label: "Tonga" },
  {
    value: "Trinidad and Tobago",
    labelAr: "ترينيداد وتوباغو",
    label: "Trinidad and Tobago",
  },
  { value: "Turkey", labelAr: "تركيا", label: "Turkey" },
  { value: "Turkmenistan", labelAr: "تركمانستان", label: "Turkmenistan" },
  {
    value: "Turks and Caicos Islands",
    labelAr: "جزر تركس وكايكوس",
    label: "Turks and Caicos Islands",
  },
  { value: "Tuvalu", labelAr: "توفالو", label: "Tuvalu" },
  { value: "Uganda", labelAr: "أوغندا", label: "Uganda" },
  { value: "Ukraine", labelAr: "أوكرانيا", label: "Ukraine" },
  {
    value: "United Kingdom of Great Britain and Northern Ireland",
    labelAr: "المملكة المتحدة",
    label: "United Kingdom of Great Britain and Northern Ireland",
  },
  {
    value: "United States Minor Outlying Islands",
    labelAr: "جزر الولايات المتحدة الصغيرة النائية",
    label: "United States Minor Outlying Islands",
  },
  {
    value: "United States of America",
    labelAr: "الولايات المتحدة الأمريكية",
    label: "United States of America",
  },
  { value: "Uruguay", labelAr: "أوروغواي", label: "Uruguay" },
  { value: "Uzbekistan", labelAr: "أوزبكستان", label: "Uzbekistan" },
  { value: "Vanuatu", labelAr: "فانواتو", label: "Vanuatu" },
  {
    value: "Venezuela (Bolivarian Republic of Venezuela)",
    labelAr: "فنزويلا",
    label: "Venezuela (Bolivarian Republic of Venezuela)",
  },
  { value: "Vietnam", labelAr: "فيتنام", label: "Vietnam" },
  {
    value: "Virgin Islands (British)",
    labelAr: "جزر العذراء البريطانية",
    label: "Virgin Islands (British)",
  },
  {
    value: "Virgin Islands (U.S.)",
    labelAr: "جزر العذراء الأمريكية",
    label: "Virgin Islands (U.S.)",
  },
  {
    value: "Wallis and Futuna",
    labelAr: "واليس وفوتونا",
    label: "Wallis and Futuna",
  },
  {
    value: "Western Sahara",
    labelAr: "الصحراء الغربية",
    label: "Western Sahara",
  },
  { value: "Zambia", labelAr: "زامبيا", label: "Zambia" },
  { value: "Zimbabwe", labelAr: "زيمبابوي", label: "Zimbabwe" },
];
