const mapDataToSchema = (data) => {
  return data.map((item) => {
    return {
      firstName: item.FirstName,
      secondName: item.SecondName || "",
      thirdName: item.ThirdName || "",
      lastName: item.LastName || "",
      gender: item.Gender,
      nationality: item.Nationality,
      maritalStatus: item.MaritalStatus,
      religion: item.Religion,
      birthCountry: item.BirthCountry,
      email: item.EmailAddress.trim(), // remove any leading/trailing spaces
      phoneNO: item.PhoneNumber ? item.PhoneNumber.toString() : "", // convert phone to string if needed
      sector: item.Sector || "",
      sectorCode: item.SectorCode ? item.SectorCode.toString() : "",
      sectorHead: item.SectorHead || "",
      positionName: item.PositionName || "",
      division: item.Division || "",
      divisionCode: item.DivisionCode ? item.DivisionCode.toString() : "",
      divisionHeadOfUnit: item.DivisionHeadOfUnit || "",
      department: item.Department || "",
      departmentCode: item.DepartmentCode ? item.DepartmentCode.toString() : "",
      constCenterAccount: item.CostCentreAccount || "",
      constCenterAccountCode: item.CostCentreAccountCode || "",
      contractType: item.ContractType || "",
      managerID: item.ManagerID ? item.ManagerID.toString() : "",
      managerName: item.ManagerName || "",
      managerEmail: item.ManagerEmail.trim(),
      emloyeeStatus: item.EmployeeStatus || "",
      jobTitle: item.JobTitle || "",
      hireDate: item.EmployeeHireDate ? item.EmployeeHireDate.toString() : "", // convert Excel date format to string
      iqamaNumber: item.IqamaNumber ? item.IqamaNumber.toString() : "",
      iqamaExpiry: item.IqamaExpiryDate ? item.IqamaExpiryDate.toString() : "",
      passportNo: item.PassportNumber || "",
      passportIssuanceCountry: item.PassportIssuanceCountry || "",
      passportExpiry: item.PassportExpiryDate
        ? item.PassportExpiryDate.toString()
        : "",
      SNI: item.SNI ? item.SNI.toString() : "",
    };
  });
};

// Example usage
const jsonData = [
  // Your array of data as provided
];

const arr = [
  {
    EmployeeNumber: 20001241,
    FirstName: "Hussain",
    SecondName: "Talal",
    ThirdName: "Ibrahim",
    LastName: "Alsabr",
    Gender: "M",
    Nationality: "SAU",
    MaritalStatus: "Single",
    Religion: "Muslim",
    BirthCountry: "Saudi Arabia",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "Public Services Company",
    SectorCode: 20000183,
    SectorHead: "Abdulrazaq Alabdulrazaq",
    PositionName: "Applications Integration Manager",
    Division: "Technology",
    DivisionCode: 30000703,
    DivisionHeadOfUnit: "Abdulrazaq Alabdulrazaq",
    Department: "Applications",
    DepartmentCode: 40001900,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "NEOM Full Time",
    ManagerID: 20001476,
    ManagerName: "Abdulrazaq Alabdulrazaq",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "UI/UX Manager",
    EmployeeHireDate: 44431,
    SNI: 1090001280,
  },
  {
    EmployeeNumber: 20004350,
    FirstName: "Rawan",
    LastName: "Alsubhi",
    Gender: "F",
    Nationality: "SAU",
    MaritalStatus: "Single",
    Religion: "Muslim",
    BirthCountry: "Saudi Arabia",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "Public Services Company",
    SectorCode: 20000183,
    SectorHead: "Mazin Althunayan",
    PositionName: "UI/UX Manager",
    Division: "Digital",
    DivisionCode: 30000699,
    DivisionHeadOfUnit: "Mazin Althunayan",
    Department: "UI/UX",
    DepartmentCode: 40001892,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "NEOM Full Time",
    ManagerID: 10000384,
    ManagerName: "Mazin Althunayan",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Applications Integration Manager",
    EmployeeHireDate: 45165,
    SNI: 1091111289,
  },
  {
    EmployeeNumber: 20001476,
    FirstName: "Abdulrazaq",
    LastName: "Alabdulrazaq",
    Gender: "M",
    Nationality: "SAU",
    MaritalStatus: "Married",
    Religion: "Muslim",
    BirthCountry: "Saudi Arabia",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "Public Services Company",
    SectorCode: 20000183,
    SectorHead: "Abdulrazaq Alabdulrazaq",
    PositionName: "Head of Technology",
    Division: "Technology",
    DivisionCode: 30000703,
    DivisionHeadOfUnit: "Abdulrazaq Alabdulrazaq",
    Department: "Technology",
    DepartmentCode: 40001903,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "NEOM Full Time",
    ManagerID: 10000384,
    ManagerName: "Mazin Althunayan",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Head of Technology",
    EmployeeHireDate: 44536,
    PassportNumber: "Z123456",
    PassportIssuanceCountry: "Saudi Arabia",
    PassportExpiryDate: 47482,
    SNI: 1090001397,
  },
  {
    EmployeeNumber: 80000693,
    FirstName: "Muhammad",
    LastName: "Fazeel",
    Gender: "M",
    Nationality: "SAU",
    MaritalStatus: "Married",
    Religion: "Muslim",
    BirthCountry: "Jeddah",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "NEOM Authority",
    SectorCode: 20000035,
    SectorHead: "Mazin Althunayan",
    PositionName: "Senior Backend Developer (SMP)",
    Division: "Cognitive Government",
    DivisionCode: 30000677,
    DivisionHeadOfUnit: "Mazin Althunayan",
    Department: "Digital Government",
    DepartmentCode: 40000085,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "SMP",
    ManagerID: 20002871,
    ManagerName: "Abdullah Alaradi",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Product portfolio Manager",
    EmployeeHireDate: 45383,
    IqamaNumber: 2556666651,
    IqamaExpiryDate: 46386,
  },
  {
    EmployeeNumber: 80000695,
    FirstName: "Abdullah",
    SecondName: "Ali",
    ThirdName: "Mohammad",
    LastName: "Flefil",
    Gender: "M",
    Nationality: "JOR",
    MaritalStatus: "Single",
    Religion: "Muslim",
    BirthCountry: "Jordan",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "NEOM Authority",
    SectorCode: 20000035,
    SectorHead: "Mazin Althunayan",
    PositionName: "Frontend Lead (SMP)",
    Division: "Cognitive Government",
    DivisionCode: 30000677,
    DivisionHeadOfUnit: "Mazin Althunayan",
    Department: "Digital Government",
    DepartmentCode: 40000085,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "SMP",
    ManagerID: 20001241,
    ManagerName: "Hussain Alsabr",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Business Analyst Manager",
    EmployeeHireDate: 45383,
    IqamaNumber: 2556777751,
    IqamaExpiryDate: 46386,
  },
  {
    EmployeeNumber: 10000595,
    FirstName: "Ghassan",
    SecondName: "Mohammed",
    LastName: "Alghofaili",
    Gender: "M",
    Nationality: "SAU",
    MaritalStatus: "Single",
    Religion: "Muslim",
    BirthCountry: "Saudi Arabia",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "Public Services Company",
    SectorCode: 20000183,
    SectorHead: "Mazin Althunayan",
    PositionName: "Product portfolio Manager",
    Division: "Digital",
    DivisionCode: 30000699,
    DivisionHeadOfUnit: "Mazin Althunayan",
    Department: "Product Management",
    DepartmentCode: 40001891,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "NEOM Full Time",
    ManagerID: 10000384,
    ManagerName: "Mazin Althunayan",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Senior Backend Developer",
    EmployeeHireDate: 44018,
    PassportNumber: "AZ12345",
    PassportIssuanceCountry: "Saudi Arabia",
    PassportExpiryDate: 47482,
    SNI: 1086771753,
  },
  {
    EmployeeNumber: 80000691,
    FirstName: "Bara",
    SecondName: "Yassin",
    ThirdName: "Murshed",
    LastName: "Zaidan",
    Gender: "M",
    Nationality: "JOR",
    MaritalStatus: "Single",
    Religion: "Muslim",
    BirthCountry: "Jordan",
    EmailAddress: "\tdummy@neomsap.com",
    PhoneNumber: 12345678,
    Sector: "NEOM Authority",
    SectorCode: 20000035,
    SectorHead: "Mazin Althunayan",
    PositionName: "Business Analyst Manager (SMP)",
    Division: "Cognitive Government",
    DivisionCode: 30000677,
    DivisionHeadOfUnit: "Mazin Althunayan",
    Department: "Digital Government",
    DepartmentCode: 40000085,
    CostCentreAccount: "GA - Digital Government",
    CostCentreAccountCode: "NEOM9000146001",
    ContractType: "SMP",
    ManagerID: 10000595,
    ManagerName: "Ghassan Alghofaili",
    ManagerEmail: "\tdummy@neomsap.com",
    EmployeeStatus: "Active",
    JobTitle: "Frontend Lead",
    EmployeeHireDate: 45383,
    IqamaNumber: 2556776651,
    IqamaExpiryDate: 46386,
  },
];

// Convert the data to match your schema
const mappedData = mapDataToSchema(arr);

console.log(mappedData);
